# To install pre-commit, run:
#   uv run pre-commit install
#
# Pre-commit checks will then run on staged files by default.
#
# To run for all files, for debugging, testing, etc:
#   uv run pre-commit run --all-files
#
# To run a single check on all files:
#   uv run pre-commit run --all-files ruff-format
#
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: uv run mypy .
        language: system
        pass_filenames: false
        files: \.py$
